sudo: false
language: generic

before_install:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then openssl aes-256-cbc -K $encrypted_34922f73314b_key -iv $encrypted_34922f73314b_iv -in gh_rsa.enc -out gh_rsa -d; fi

script:
  - cp webpage-head.htm non-minified.html
  - curl -X POST -T README.md -H "Content-Type: text/plain;" "https://api.github.com/markdown/raw?client_id=f138068c885b89890c13&client_secret=$gh_app_secret" >> non-minified.html
  - echo '</div></div></body></html>' >> non-minified.html
  - curl -X POST --form-string "html=$(cat non-minified.html)" www.willpeavy.com/minifier/ | tr -d '\n\r' | sed -e 's/.*<p><textarea id="html" name="html">//' -e 's:</textarea></p>.*::' -e 's/> </></g' | perl -pe 's|( ?)/\*.*?\*/( ?)||g' > ../index.html

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then echo "Update webpage for commits $TRAVIS_COMMIT_RANGE" > $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then echo >> $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then git log $TRAVIS_COMMIT_RANGE --pretty=oneline >> $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then git clone -b gh-pages git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_BUILD_DIR-gh-pages; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then cd $TRAVIS_BUILD_DIR-gh-pages; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then cp ../index.html .; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then git config --global user.email "nabijaczleweli@gmail.com" && git config --global user.name "Nabijaczleweli Autouploader Bot" && git config --global push.default simple; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then git add * && git commit -F $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then git push && cd $TRAVIS_BUILD_DIR; fi
